### ISSUE TITLE
data file keeps 0 values.

### ISSUE THREAD

**Issue by andrewkm** [JamieSinn/ClaimLevels#2]
The data file should not keep 0 values. For some reason we suddenly have tons of them. Perhaps when a player uses the /credits command it generates an entry?

Who knows, but all 0 entries should be gone from the file, this was a bug long ago that the original developer fixed.

**Comment by JamieSinn** [comment]
Okay, Will fix.

**Comment by JamieSinn** [comment]
... why you no close github.
